services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./common/docker/
    working_dir: /code
    environment:
      - AWS_REGION=eu-central-1
      - AWS_PROFILE
      - PGP_KEY_BASE64
      - ID_RSA_BASE64
    volumes:
      - $HOME/.aws/:/root/.aws/
      - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts
      - $HOME/.ssh/known_hosts.old:/root/.ssh/known_hosts.old
      - .:/code
