services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./common/docker/
    working_dir: /code
    environment:
      - AWS_REGION=eu-central-1
      - AWS_PROFILE
      - PGP_KEY_BASE64
    volumes:
      - $HOME/.aws/:/root/.aws/
      - .:/code
