services:
  app:
    build:
      dockerfile: ./common/docker/Dockerfile
      context: .
    working_dir: /code
    environment:
      - AWS_REGION=eu-central-1
      - AWS_PROFILE
    volumes:
      - $HOME/.aws/:/root/.aws/
      - .:/code
